# Generated by Django 4.1.7 on 2023-03-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shopper_username_alter_shopper_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopper',
            managers=[
            ],
        ),
    ]
