# Generated by Django 4.1.7 on 2023-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
